### ISSUE TITLE
setup error

### ISSUE THREAD

**Issue by ghost** [ledgersmb/ledgersmb-docker#20]
i follow the setup process and i got this after filling in a user
Error!

Can't call method "msg" on unblessed reference at /srv/ledgersmb/tools/../lib/LedgerSMB/Request.pm line 61.

dbversion: 1.5.20, company:
Status: 500 Internal server error (PSGI.pm run_new)

**Comment by veto64** [comment]
ok, i tried again, and after filling in all user data including tax and employee id what are not required i could get to the next page

**Comment by ehuelsmann** [comment]
Thanks for reporting this problem. From your description of the solution I conclude this is an issue with the application itself, not with the docker image.

Problems with the application itself can be reported in https:///github.com/ledgersmb/LedgerSMB/issues ; I've taken note of your issue with the way things stand. I'll test if (most) of them have been solved in 1.6. If not, I'll make sure the remainder is solved in 1.7.
