### ISSUE TITLE
1.6 - font selection of cmss not applying

### ISSUE THREAD

**Issue by freelock** [ledgersmb/ledgersmb-docker#23]
When generating a PDF in 1.6 that specifies the 'cmss' font - Computer Modern Sans Serif - the resulting PDF uses a Serif font. This is using the Docker ledgersmb/ledgersmb:1.6 container.

**Comment by ehuelsmann** [comment]
@freelock ping!

**Comment by ehuelsmann** [comment]
No response in 90 days... closing.

**Comment by ehuelsmann** [comment]
Actually, I think this is caused by a missing dependency on the package `texlive-fonts-recommended` (I just ran into that problem in the development image). I'll add the dependency on all active branches.
