### ISSUE TITLE
Error in docker-compose.yml

### ISSUE THREAD

**Issue by GHamblin** [ledgersmb/ledgersmb-docker#24]
This is the error I receive:
docker-compose up
ERROR: yaml.scanner.ScannerError: mapping values are not allowed here
  in "./docker-compose.yml", line 118, column 73

This is line 118:
       <span class="progress-pjax-loader-bar top-0 left-0" style="width: 0%;"></span>

**Comment by GHamblin** [comment]
"       <span class="progress-pjax-loader-bar top-0 left-0" style="width: 0%;"></span>"

**Comment by GHamblin** [comment]
Nevermind. I screwed up.

**Comment by ehuelsmann** [comment]
Thanks for taking the time to file the issue anyway!
