### ISSUE TITLE
Unable to log in when installing using docker-compose 

### ISSUE THREAD

**Issue by bruceschaller** [ledgersmb/ledgersmb-docker#25]
After installing with docker-compose pull & docker-compose up, attempting to log on with default database username / password / company - postgres / abc / postgres fails with the following output to the console terminal:

`postgres_1  | LOG:  database system is ready to accept connections
postgres_1  | LOG:  autovacuum launcher started
lsmb_1      | Req:2A5BA8809D4A11EA830E87B288A30552 ::ffff:192.168.192.1 - - [23/May/2020:23:07:25 +0000] "GET /login.pl HTTP/1.1" 200 4050 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"
lsmb_1      | Req:304E40FE9D4A11EA830E87B288A30552 ::ffff:192.168.192.1 - - [23/May/2020:23:07:35 +0000] "GET /login.pl?action=authenticate&company=postgres HTTP/1.1" 401 29 "http://127.0.0.1:5762/login.pl" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"
postgres_1  | ERROR:  function session_create() does not exist at character 15
postgres_1  | HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
postgres_1  | STATEMENT:  SELECT * FROM session_create();
lsmb_1      | Req:304F34149D4A11EA830E87B288A30552 2020/05/23 23:07:35 - ERROR - LedgerSMB::PSGI::catch {...}  lib/LedgerSMB/PSGI.pm (136) -- ERROR:  function session_create() does not exist\nLINE 1: SELECT * FROM session_create();\n                      ^\nHINT:  No function matches the given name and argument types. You might need to add explicit type casts. at lib/LedgerSMB/Middleware/AuthenticateSession.pm line 228.\n
lsmb_1      | Req:304F34149D4A11EA830E87B288A30552 ::ffff:192.168.192.1 - - [23/May/2020:23:07:35 +0000] "GET /login.pl?action=authenticate&company=postgres HTTP/1.1" 500 408 "http://127.0.0.1:5762/login.pl" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"
`

For resolution of this bug I'll pay $100 USD - notify me that bug is closed, let me test, and provide a paypal email and whoever closes it first gets the bounty.  Cheers and thank you!

**Comment by sbts** [comment]
@bruceschaller Hi, I'm going to need a little extra info to be able to help you.

Could you please provide a screenshot of the LOGIN screen with the info you are trying to use filled in.

Also, did you make any edits to the docker-compose.yml file?

Thanks for the report.

**Comment by sbts** [comment]
@bruceschaller I've just spun up a clean instance here to test with.
Assuming you have made no edits to docker-compose.yml once you start the compose stack you will need to first visit
- http://172.19.03:5764/setup.pl  - note: you will need to use the correct IP address to match what your container received.

From there, you will need to enter
- username : postgres
- password : abc
- database  : the name of the new database you want to create
- click on "Create"
NOTE: do not click on "Login" at this point you need to first create the DB.

From here you will need to follow the prompts. 
There is documentation available in the [LedgerSMB repository](https://github.com/ledgersmb/LedgerSMB) and on the [Project Website](https://ledgersmb.org)

Once the DB (and First User) have been created you can then login to the application at
- http://172.19.0.3:5762/login.pl

If you have any issues completing this process, or learning to use LedgerSMB feel free to come and ask questions in one of our support channels.
- https://riot.im/app/#/room/#ledgersmb

Is our preferred "live" chat platform.
A full list of support channels is available on our website [here](https://ledgersmb.org/topics/support)

I believe this should be adequate to cover your requirements.

**Comment by bruceschaller** [comment]
You already have helped!  

I was trying from to login.pl and not setup.pl on 1st fun.  I can't believe I missed it!

I wish the error in doing this had been more descriptive, but now I know it.

I'm excited to learn more about how this works, and so happy to see open source projects like this one improving the space in which they operate.

I'm happy to send that bounty- just say where.
