### ISSUE TITLE
[1.9] Docker yaml pulls in postgres 9.6, but LedgerSMB 1.9 has a requirement for 10+

### ISSUE THREAD

**Issue by neilt** [ledgersmb/ledgersmb-docker#28]
The docker yaml file for 1.9 branch pulls in Postgres 9.6, but the readme for ledgersmb branch 1.9 indicates that the minimum Postgres version is 10+.

**Comment by ehuelsmann** [comment]
Closed by 49a448c

**Comment by ehuelsmann** [comment]
Thanks for the report!
