### ISSUE TITLE
Suggestion: Redirect / to /login.pl

### ISSUE THREAD

**Issue by mikl** [ledgersmb/ledgersmb-docker#3]
A small, but annoying problem I have with my LedgerSMB/Docker installation is that when I go to https://ledgersmb.example.net/ (i.e. the root of the LedgerSMB server), I get hit with the HTTP Basic Auth dialog, or sometimes an error message.

It would be great if the `/` URL would instead redirect to `/login.pl`.

**Comment by ehuelsmann** [comment]
Will be fixed for 1.5.2 in the LedgerSMB repository in a sec. Closing.

**Comment by ehuelsmann** [comment]
1.5.2 was released. So is the 1.5.2 container. Please feel free to re-open if the solution doesn't match your expectation.
