### ISSUE TITLE
Cannot use custom configuration file

### ISSUE THREAD

**Issue by freelock** [ledgersmb/ledgersmb-docker#31]
The current start.sh script generates a /tmp/ledgersmb.conf on first run or any startup when this file doesn't already exist, with contents embedded in start.sh. It then sets the LSMB_CONFIG_FILE path to use it.

This makes it so you cannot easily set any options easily in a child Dockerfile -- when the image is built, the /tmp/ledgersmb.conf file does not exist, and the /tmp directory is subject to getting clobbered anyway.

Need to change start.sh to copy its necessary config from a file that could be replaced later in another Dockerfile.

**Comment by ehuelsmann** [comment]
0f7242d5597e61641f5cd28427064cd7293a000f may have addressed this issue.
