### ISSUE TITLE
exec /usr/local/bin/start.sh on lsmb container

### ISSUE THREAD

**Issue by jaxonashton** [ledgersmb/ledgersmb-docker#34]
### Version

1.10

### What browsers are you seeing the problem on?

This problem isn't browser related

### What happened?

When starting the docker container, an error presents as follows:

![image](https://github.com/ledgersmb/LedgerSMB/assets/3246415/238e8579-aebb-4376-9cea-9305b885de3b)

### What should have happened?

The docker container should fire up with out error and allow me to navigate to `http://localhost:5762/setup.pl`

**Comment by ehuelsmann** [comment]
Fixed.
