### ISSUE TITLE
Improve LSMB Docker images to work with Raspberry Pi

### ISSUE THREAD

**Issue by neilt** [ledgersmb/ledgersmb-docker#36]
The problem for me is that Docker is only available for AMD64 architecture,
not the armhf of the Raspberry Pi. The Raspberry Pi is a low cost option
for small business accounting - AU$170 for the Pi400 kit and AU$110 for a
21" screen - nothing else required 😀

_Originally posted by @howardlowndes in https://github.com/ledgersmb/LedgerSMB/issues/7797#issuecomment-1859146773_

**Comment by ehuelsmann** [comment]
Implemented in our release procedure in https://github.com/ledgersmb/ledgersmb-release-tools/commit/f2d884c726bbd04d5aea581b09bf111ec799f17f
