### ISSUE TITLE
Confusing and incorrect instructions for installing ledgersmb-docker

### ISSUE THREAD

**Issue by howardlowndes** [ledgersmb/ledgersmb-docker#37]
Google **ledgersmb docker** and you are offered ledgersmb/ledgersmb-docker
Click **Code** and click **Download ZIP**
Download the .zip and extract it into a unique folder.
**cd** to that folder and list it

> howard@raspi-office:/home/howard/Extracts/ledgersmb-docker-1.11 $ ls -l
total 40
-rw-r--r-- 1 howard howard   908 Dec 16 08:33 docker-compose-reverseproxy.yml
-rw-r--r-- 1 howard howard  3448 Dec 16 08:33 docker-compose.yml
-rw-r--r-- 1 howard howard  5093 Dec 16 08:33 Dockerfile
-rw-r--r-- 1 howard howard  1963 Dec 16 08:33 nginx.conf
-rw-r--r-- 1 howard howard 11440 Dec 16 08:33 README.md
-rwxr-xr-x 1 howard howard  4721 Dec 16 08:33 start.sh
howard@raspi-office:~/Extracts/ledgersmb-docker-1.11 $ 

Note that everything is dated Dec 16 so it's all current.
Read the README.md --- not very intuitve...
Note the presence of a **start.sh** script which is executable so run **./start.sh** and get

> ./start.sh: line 3: cd: /srv/ledgersmb: No such file or directory
mkdir: cannot create directory ‘./local/conf/’: No such file or directory
./start.sh: line 72: ./local/conf/ledgersmb.yaml: No such file or directory
--------- LEDGERSMB CONFIGURATION:  ledgersmb.conf
cat: ./local/conf/ledgersmb.yaml: No such file or directory
--------- LEDGERSMB CONFIGURATION --- END
Can't locate Plack/Runner.pm in @INC (you may need to install the Plack::Runner module) (@INC contains: /home/howard/perl5/lib/perl5/arm-linux-gnueabihf-thread-multi-64int /home/howard/perl5/lib/perl5 /etc/perl /usr/local/lib/arm-linux-gnueabihf/perl/5.36.0 /usr/local/share/perl/5.36.0 /usr/lib/arm-linux-gnueabihf/perl5/5.36 /usr/share/perl5 /usr/lib/arm-linux-gnueabihf/perl-base /usr/lib/arm-linux-gnueabihf/perl/5.36 /usr/share/perl/5.36 /usr/local/lib/site_perl) at /usr/local/bin/starman line 3.
BEGIN failed--compilation aborted at /usr/local/bin/starman line 3.

Study line 3 of the script and see that it refers to **/srv/ledgersmb**
Run **ls -l /srv** and discover that it's am empty folder owned by root.root
Try running the script under **sudo** - same result.

Raise a bug report

**Comment by ehuelsmann** [comment]
With the new table of contents in the README, you should be able to find a reference to the installation instructions in the README.
