### ISSUE TITLE
Change docker-compose-reverseproxy server ip and port

### ISSUE THREAD

**Issue by lifeboy** [ledgersmb/ledgersmb-docker#38]
I would like to install the docker version using the nginx reverseproxy docker, but there is no sense in running this on localhost:8080 when my server doesn't have a GUI.  Where does one change the config to that nginx will start on the ip of the server and port 80?  

I would actually like to add cerbot into the package as well, but I'll take one step at a time.

**Comment by ehuelsmann** [comment]
Hi!

This bit:

https://github.com/ledgersmb/ledgersmb-docker/blob/5670f5760fe78adbc381ac08da5cf6ce063a4e80/docker-compose-reverseproxy.yml#L26-L27

exposes the container on all interfaces of the host, both localhost as well as the ip address associated with "eth0"; both on port 8080. If you want to expose the reverseproxy on another port, the section should read:

```yaml
ports:
  - "<anotherport>:8080"
```

Is there anything in particular that made you think it would only be exposed on `localhost:8080`? Because if that's the case, we probably should change the description.

**Comment by lifeboy** [comment]
Ah, that addresses the port part, but from this it is clear that it's only exposed on localhost.

```
root@ledgersmb:~/ledgersmb-docker# docker-compose -f docker-compose.yml -f docker-compose-reverseproxy.yml  up -d
[+] Running 4/4
 ✔ Volume "ledgersmb-docker_lsmbdata"     Created 
 ✔ Container ledgersmb-docker-postgres-1  Started 
 ✔ Container ledgersmb-docker-lsmb-1      Started 
 ✔ Container ledgersmb-docker-proxy-1     Started 
root@ledgersmb:~/ledgersmb-docker# netstat -tunap
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      591/systemd-resolve 
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      668/sshd: /usr/sbin 
tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN      2987/docker-proxy   
tcp        0      0 0.0.0.0:5762            0.0.0.0:*               LISTEN      2885/docker-proxy   
tcp        0      0 192.168.161.101:22      192.168.131.150:34256   ESTABLISHED 2547/sshd: root@pts 
tcp6       0      0 :::8080                 :::*                    LISTEN      2993/docker-proxy   
tcp6       0      0 :::5762                 :::*                    LISTEN      2890/docker-proxy   
udp        0      0 127.0.0.53:53           0.0.0.0:*                           591/systemd-resolve 

```

**Comment by ehuelsmann** [comment]
From your paste, these are the important lines:

```plain
tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN      2987/docker-proxy   
tcp        0      0 0.0.0.0:5762            0.0.0.0:*               LISTEN      2885/docker-proxy   
tcp6       0      0 :::8080                 :::*                    LISTEN      2993/docker-proxy   
tcp6       0      0 :::5762                 :::*                    LISTEN      2890/docker-proxy   
```

It shows that the container/docker-proxy is listening on address `0.0.0.0:8080` and `0.0.0.0:5762` (for IPv4). The address `0.0.0.0` means "any interface on this machine", which amounts to "localhost as well as public interfaces". For IPv6, `::` is the address being listened on (as seen from the lines `:::8080` and `:::5762`, which can also be written as `[::]:8080` and `[::]:5752`). The `::` address in IPv6 is the all-zeros address like the `0.0.0.0` address in IPv4 and it should have the same effect.

If you have problems reaching these ports from other machines, could it be that a firewall (on either end) is preventing communications?

Regards,

Erik.

**Comment by lifeboy** [comment]
Of course you're perfectly correct!  I don't know what I was thinking when I posted this...   0.0.0.0 means all addresses on that machine.  Sorry for wasting your time with this!
