### ISSUE TITLE
Make Postgres port configurable at run time

### ISSUE THREAD

**Issue by freelock** [ledgersmb/ledgersmb-docker#4]
From [Matrix](https://vector.im/develop/#/room/!qyoLumPqusaXqFJNyK:matrix.org/$1471406646130672qycNA:matrix.org)

> (Ylavoie) John For our docker image, could we default to 5432 but allow overriding. This would enable installing on another version.

**Comment by freelock** [comment]
Clarification - LedgerSMB does not listen to 5432 -- this is the postgres port. It sounds like there is no need to support changing the Starman port, and after discussion this is no longer currently blocking anyone -- but might be a useful feature to allow setting a postgres port in the ledgersmb.conf file at container run time (and default_db).

**Comment by einhverfr** [comment]
wondering.....

docker-compose allows you to specify port forwarding maps, right?  And this seems like it must be a core feature of Docker.  So how do we specify this?

**Comment by einhverfr** [comment]
Also reading https://www.ctl.io/developers/blog/post/docker-networking-rules/ -- expose just exposes locally but -p allows you to publish a docker port as a host port (but not necessarily the same port).

So I am wondering if that is sufficient.

**Comment by freelock** [comment]
@einhverfr Yes, I think @ylavoie was a little confused about this. He agreed he doesn't need to change the port the container exposes -- he did think it useful to allow specifying an alternate Postgres port to consume. Which, if you're not running Postgres inside a container, is the standard way of running multiple versions/instances of Postgres on a host...

**Comment by einhverfr** [comment]
In this case, maybe we should close it as "already supported."

**Comment by freelock** [comment]
To clarify: the current image supports specifying a POSTGRES_HOST variable. This issue is to add support for a POSTGRES_PORT variable, and while we're at it, DEFAULT_DB.

**Comment by einhverfr** [comment]
what is the use case?

**Comment by freelock** [comment]
Connecting LSMB to a Postgres server that is running on an alternate port.

**Comment by einhverfr** [comment]
On the same docker image or on a different one?  (If a different one, then still not clear)

**Comment by einhverfr** [comment]
I mean is the goal to run multiple PostgreSQL instances on the same Docker?

**Comment by einhverfr** [comment]
ah you want to run ledgersmb in one container and consume PostgreSQL in a different one on a different port?  Yeah that makes sense actually.

**Comment by freelock** [comment]
@einhverfr yes exactly -- I generally follow the 1 daemon per container model, so I don't bundle postgres in the lsmb image (or apache, nginx, etc -- just starman).

You might also want to run a dedicated bare-metal DB server, not in a container at all -- if you run postgres in a container this probably isn't needed because you can connect directly to the postgres container -- but if you have a bare-metal host running Postgres, different story.

**Comment by einhverfr** [comment]
Yeah, that makes sense.

One of the huge headaches I have been battling for a couple days has been a docker-based Hadoop cluster, and one of the major headaches, I think, is caused by several HBase services running on one container (so it doesn't get killed right, and so another container can't get killed, and if you restart docker, it gets in an inconsistent state to the point where you cannot even restart your computer without a hard power off).

I am all for the one service per container model if one is going to go with Docker......

**Comment by freelock** [comment]
Fixed on all active branches.
