### ISSUE TITLE
Ownership of www-data home should be set

### ISSUE THREAD

**Issue by ylavoie** [ledgersmb/ledgersmb-docker#7]
www-data points to /var/www which is owned by root.

**Comment by ylavoie** [comment]
On dev branches only.

**Comment by sbts** [comment]
@ylavoie I'm not convinced that this is necessary.
Instead we need to fix the reasons tests want to write to the dir instead

**Comment by ehuelsmann** [comment]
If anything, this is an issue for the dev images, not the production ones. See the ledgersmb-dev-docker repository for more.
